class ScenarioSummary {
  const ScenarioSummary({
    required this.id,
    required this.name,
    required this.description,
    required this.category,
    required this.difficulty,
    required this.estimatedMinutes,
  });

  final int id;
  final String name;
  final String description;
  final String category; // travel | business | daily
  final String difficulty; // beginner | intermediate | advanced
  final int estimatedMinutes;

  String get categoryLabel {
    switch (category) {
      case 'travel':
        return '旅行';
      case 'business':
        return 'ビジネス';
      case 'daily':
        return '日常会話';
      default:
        return category;
    }
  }
}

/// Next.js 側の `SCENARIO_LIST` をベースにした静的定義。
const List<ScenarioSummary> kScenarioList = [
  ScenarioSummary(
    id: 1,
    name: '空港チェックイン',
    description: 'チェックインから搭乗までの一連の流れを練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 2,
    name: 'ビジネスミーティング',
    description: '会議での発言や合意形成に必要な表現を学習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 3,
    name: 'レストランでの注文',
    description: '予約から注文、会計までの会話パターンを習得',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 4,
    name: 'オンライン商談',
    description: 'リモートミーティングでの説明や質問に対応',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 30,
  ),
  ScenarioSummary(
    id: 5,
    name: 'ホテルチェックイン',
    description: '予約確認から要望の伝え方までを網羅',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 6,
    name: '最高のバケーション',
    description: '理想の休暇プランを説明しながら旅行英会話を練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 7,
    name: '日本を案内する',
    description: '海外の友人に日本の観光地や文化を英語で紹介',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 8,
    name: '入国審査・税関で',
    description: '入国審査と税関のやり取りを想定した実践的な会話',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 9,
    name: '旅行計画を友達と相談',
    description: '友人と旅行計画を立てながら提案・調整の表現を学ぶ',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 10,
    name: '財布を無くして警察に相談',
    description: 'トラブル時に状況を説明して助けを求める表現を練習',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 11,
    name: 'カスタマーサービスに相談',
    description: '商品の不具合やトラブルをカスタマーサービスに伝える',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 12,
    name: 'おしゃれカフェで店員と雑談',
    description: '注文に加えて軽い雑談を交えたカジュアルな会話',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 13,
    name: 'ショーチケットを入手',
    description: 'チケットの種類や席を確認しながら購入する会話',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  ),
  ScenarioSummary(
    id: 14,
    name: '公園で雑談',
    description: '初対面の人と趣味や天気について気軽に話す練習',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  ),
  ScenarioSummary(
    id: 15,
    name: 'ミーティングをリスケする',
    description: '予定変更の依頼と代替案の提案を丁寧に伝える',
    category: 'business',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  ),
  ScenarioSummary(
    id: 16,
    name: 'ミーティングを立てる',
    description: '関係者に日程候補を提示しながら会議を設定する',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 17,
    name: '会議を進行する',
    description: '議題の提示から議論の整理まで会議進行の英語表現',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 18,
    name: '契約条件の交渉',
    description: '価格や条件の違いを整理しながら合意点を探る',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 19,
    name: '顧客満足度の調査結果をプレゼン',
    description: '調査結果を分かりやすく説明し示唆を伝えるプレゼン',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 20,
    name: 'プロジェクトの遅延を謝罪する',
    description: '遅延の理由と今後の対策を誠実に説明する表現を練習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 21,
    name: '体調不良で休む',
    description: '体調不良を丁寧に伝え、代替対応を相談する会話',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
  ),
  // --- 追加シナリオ: 日常会話 (daily) ---
  ScenarioSummary(
    id: 22,
    name: '病院で症状を説明',
    description: '体調不良の症状を医師に詳しく伝える',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 23,
    name: '薬局で薬を購入',
    description: '症状を伝えて適切な薬を選んでもらう',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 24,
    name: '歯医者で予約・相談',
    description: '歯の痛みを説明し予約を取る',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  ),
  ScenarioSummary(
    id: 25,
    name: 'スーパーで店員に質問',
    description: '商品の場所や代替品について尋ねる',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 26,
    name: '服屋で試着・相談',
    description: 'サイズや色違いについて店員と話す',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 27,
    name: '美容院で髪型をオーダー',
    description: '希望のスタイルを具体的に伝える',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 28,
    name: '携帯ショップで契約相談',
    description: 'プランの比較や手続きについて相談',
    category: 'daily',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 29,
    name: '家電量販店で相談',
    description: '製品の違いやおすすめを聞く',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 30,
    name: 'オンライン注文の問い合わせ',
    description: '配送状況や返品について電話で確認',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 31,
    name: '不動産屋で部屋探し',
    description: '希望条件を伝えて物件を紹介してもらう',
    category: 'daily',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 32,
    name: '引っ越し業者に見積もり依頼',
    description: '荷物量や日程を伝えて見積もりを取る',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 33,
    name: '修理業者を呼ぶ',
    description: '故障状況を説明し修理を依頼する',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 34,
    name: '隣人に挨拶・自己紹介',
    description: '引っ越し後の挨拶と軽い会話',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 35,
    name: '郵便局で荷物を送る',
    description: '送り先や配送方法を選んで発送',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 36,
    name: '銀行で口座開設',
    description: '必要書類や口座種類について相談',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 37,
    name: '図書館で本を探す',
    description: '読みたい本を司書に相談して探す',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 38,
    name: '友人を食事に誘う',
    description: '予定を聞いてレストランを提案',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 39,
    name: 'パーティーで初対面の人と会話',
    description: '自己紹介から共通の話題を見つける',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 40,
    name: '習い事の体験申し込み',
    description: 'ヨガや料理教室の体験レッスンを申し込む',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 41,
    name: 'ジムに入会する',
    description: '料金プランや設備について質問して契約',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  // --- 追加シナリオ: 旅行 (travel) ---
  ScenarioSummary(
    id: 42,
    name: '機内でCAにリクエスト',
    description: '飲み物や毛布を頼む、座席変更を相談',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 43,
    name: '乗り継ぎ便を確認',
    description: '遅延時の対応やゲート変更を確認',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  ),
  ScenarioSummary(
    id: 44,
    name: '荷物が届かない！',
    description: 'ロストバゲージの状況説明と対応依頼',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 45,
    name: '空港でフライト変更',
    description: '予約変更やキャンセルの手続き',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 46,
    name: 'レンタカーを借りる',
    description: '車種選択、保険、返却方法を確認',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 47,
    name: '電車・バスのチケット購入',
    description: '行き先と時間を伝えてチケットを買う',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 48,
    name: 'ホテルの部屋に問題発生',
    description: 'エアコン故障や清掃不備を報告',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 49,
    name: 'ルームサービスを注文',
    description: 'メニューを見て電話で注文',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 50,
    name: 'レイトチェックアウトを交渉',
    description: '延長料金や空き状況を確認して依頼',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  ),
  ScenarioSummary(
    id: 51,
    name: 'Airbnbホストとやりとり',
    description: 'チェックイン方法や設備について質問',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 52,
    name: '観光案内所で情報収集',
    description: 'おすすめスポットやアクセスを聞く',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 53,
    name: '現地ツアーに申し込む',
    description: 'ツアー内容を確認して予約',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  ),
  ScenarioSummary(
    id: 54,
    name: '美術館・博物館で質問',
    description: '展示物や音声ガイドについて尋ねる',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 55,
    name: '写真を撮ってもらう',
    description: '通行人にお願いして撮影してもらう',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 10,
  ),
  ScenarioSummary(
    id: 56,
    name: '現地の人におすすめを聞く',
    description: 'レストランや穴場スポットを教えてもらう',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  ),
  ScenarioSummary(
    id: 57,
    name: '道に迷って助けを求める',
    description: '地図を見せながら行き方を聞く',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
  ScenarioSummary(
    id: 58,
    name: '体調不良で現地の病院へ',
    description: '症状を説明し保険書類を提示',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 59,
    name: 'パスポート紛失の対応',
    description: '大使館への連絡と再発行手続き',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  ),
  ScenarioSummary(
    id: 60,
    name: '両替所で両替',
    description: 'レートを確認して両替を依頼',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 10,
  ),
  ScenarioSummary(
    id: 61,
    name: 'お土産屋で買い物',
    description: '商品の説明を聞いてお土産を選ぶ',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  ),
];

/// Freeプランで解放する固定シナリオ（3つ）
///
/// - travel / business / daily を1つずつにして、体験の偏りを防ぐ
const Set<int> kFreeScenarioIds = {1, 2, 3};


