import { ScenarioDetail, ScenarioSummary } from '@/types/scenario'

export const SCENARIO_CATEGORIES = [
  {
    id: 'travel',
    label: '旅行',
    description: '空港・ホテル・移動など旅行時の会話を想定',
  },
  {
    id: 'business',
    label: 'ビジネス',
    description: 'ミーティング・商談・メール対応など',
  },
  {
    id: 'daily',
    label: '日常会話',
    description: '日常生活でよく使う会話を中心に',
  },
]

export const SCENARIO_LIST: ScenarioSummary[] = [
  {
    id: 1,
    name: '空港チェックイン',
    description: 'チェックインから搭乗までの一連の流れを練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 2,
    name: 'ビジネスミーティング',
    description: '会議での発言や合意形成に必要な表現を学習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 3,
    name: 'レストランでの注文',
    description: '予約から注文、会計までの会話パターンを習得',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 4,
    name: 'オンライン商談',
    description: 'リモートミーティングでの説明や質問に対応',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 30,
  },
  {
    id: 5,
    name: 'ホテルチェックイン',
    description: '予約確認から要望の伝え方までを網羅',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  // --- Issue #27: 追加対象シナリオ ---
  // travel
  {
    id: 6,
    name: '最高のバケーション',
    description: '理想の休暇プランを説明しながら旅行英会話を練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 7,
    name: '日本を案内する',
    description: '海外の友人に日本の観光地や文化を英語で紹介',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 8,
    name: '入国審査・税関で',
    description: '入国審査と税関のやり取りを想定した実践的な会話',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 18,
  },
  {
    id: 9,
    name: '旅行計画を友達と相談',
    description: '友人と旅行計画を立てながら提案・調整の表現を学ぶ',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  // daily
  {
    id: 10,
    name: '財布を無くして警察に相談',
    description: 'トラブル時に状況を説明して助けを求める表現を練習',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 11,
    name: 'カスタマーサービスに相談',
    description: '商品の不具合やトラブルをカスタマーサービスに伝える',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 12,
    name: 'おしゃれカフェで店員と雑談',
    description: '注文に加えて軽い雑談を交えたカジュアルな会話',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 13,
    name: 'ショーチケットを入手',
    description: 'チケットの種類や席を確認しながら購入する会話',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  },
  {
    id: 14,
    name: '公園で雑談',
    description: '初対面の人と趣味や天気について気軽に話す練習',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  },
  // business
  {
    id: 15,
    name: 'ミーティングをリスケする',
    description: '予定変更の依頼と代替案の提案を丁寧に伝える',
    category: 'business',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  },
  {
    id: 16,
    name: 'ミーティングを立てる',
    description: '関係者に日程候補を提示しながら会議を設定する',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 17,
    name: '会議を進行する',
    description: '議題の提示から議論の整理まで会議進行の英語表現',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 18,
    name: '契約条件の交渉',
    description: '価格や条件の違いを整理しながら合意点を探る',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 19,
    name: '顧客満足度の調査結果をプレゼン',
    description: '調査結果を分かりやすく説明し示唆を伝えるプレゼン',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 20,
    name: 'プロジェクトの遅延を謝罪する',
    description: '遅延の理由と今後の対策を誠実に説明する表現を練習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 21,
    name: '体調不良で休む',
    description: '体調不良を丁寧に伝え、代替対応を相談する会話',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
  },
  // --- 追加シナリオ: 日常会話 (daily) ---
  {
    id: 22,
    name: '病院で症状を説明',
    description: '体調不良の症状を医師に詳しく伝える',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 23,
    name: '薬局で薬を購入',
    description: '症状を伝えて適切な薬を選んでもらう',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 24,
    name: '歯医者で予約・相談',
    description: '歯の痛みを説明し予約を取る',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  },
  {
    id: 25,
    name: 'スーパーで店員に質問',
    description: '商品の場所や代替品について尋ねる',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 26,
    name: '服屋で試着・相談',
    description: 'サイズや色違いについて店員と話す',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 27,
    name: '美容院で髪型をオーダー',
    description: '希望のスタイルを具体的に伝える',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 28,
    name: '携帯ショップで契約相談',
    description: 'プランの比較や手続きについて相談',
    category: 'daily',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 29,
    name: '家電量販店で相談',
    description: '製品の違いやおすすめを聞く',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 30,
    name: 'オンライン注文の問い合わせ',
    description: '配送状況や返品について電話で確認',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 31,
    name: '不動産屋で部屋探し',
    description: '希望条件を伝えて物件を紹介してもらう',
    category: 'daily',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 32,
    name: '引っ越し業者に見積もり依頼',
    description: '荷物量や日程を伝えて見積もりを取る',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 33,
    name: '修理業者を呼ぶ',
    description: '故障状況を説明し修理を依頼する',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 34,
    name: '隣人に挨拶・自己紹介',
    description: '引っ越し後の挨拶と軽い会話',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 35,
    name: '郵便局で荷物を送る',
    description: '送り先や配送方法を選んで発送',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 36,
    name: '銀行で口座開設',
    description: '必要書類や口座種類について相談',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 37,
    name: '図書館で本を探す',
    description: '読みたい本を司書に相談して探す',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 38,
    name: '友人を食事に誘う',
    description: '予定を聞いてレストランを提案',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 39,
    name: 'パーティーで初対面の人と会話',
    description: '自己紹介から共通の話題を見つける',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 40,
    name: '習い事の体験申し込み',
    description: 'ヨガや料理教室の体験レッスンを申し込む',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 41,
    name: 'ジムに入会する',
    description: '料金プランや設備について質問して契約',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  // --- 追加シナリオ: 旅行 (travel) ---
  {
    id: 42,
    name: '機内でCAにリクエスト',
    description: '飲み物や毛布を頼む、座席変更を相談',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 43,
    name: '乗り継ぎ便を確認',
    description: '遅延時の対応やゲート変更を確認',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  },
  {
    id: 44,
    name: '荷物が届かない！',
    description: 'ロストバゲージの状況説明と対応依頼',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 45,
    name: '空港でフライト変更',
    description: '予約変更やキャンセルの手続き',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 46,
    name: 'レンタカーを借りる',
    description: '車種選択、保険、返却方法を確認',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 47,
    name: '電車・バスのチケット購入',
    description: '行き先と時間を伝えてチケットを買う',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 48,
    name: 'ホテルの部屋に問題発生',
    description: 'エアコン故障や清掃不備を報告',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 49,
    name: 'ルームサービスを注文',
    description: 'メニューを見て電話で注文',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 50,
    name: 'レイトチェックアウトを交渉',
    description: '延長料金や空き状況を確認して依頼',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  },
  {
    id: 51,
    name: 'Airbnbホストとやりとり',
    description: 'チェックイン方法や設備について質問',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 52,
    name: '観光案内所で情報収集',
    description: 'おすすめスポットやアクセスを聞く',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 53,
    name: '現地ツアーに申し込む',
    description: 'ツアー内容を確認して予約',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 54,
    name: '美術館・博物館で質問',
    description: '展示物や音声ガイドについて尋ねる',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 55,
    name: '写真を撮ってもらう',
    description: '通行人にお願いして撮影してもらう',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 10,
  },
  {
    id: 56,
    name: '現地の人におすすめを聞く',
    description: 'レストランや穴場スポットを教えてもらう',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  },
  {
    id: 57,
    name: '道に迷って助けを求める',
    description: '地図を見せながら行き方を聞く',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 58,
    name: '体調不良で現地の病院へ',
    description: '症状を説明し保険書類を提示',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 59,
    name: 'パスポート紛失の対応',
    description: '大使館への連絡と再発行手続き',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 60,
    name: '両替所で両替',
    description: 'レートを確認して両替を依頼',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 10,
  },
  {
    id: 61,
    name: 'お土産屋で買い物',
    description: '商品の説明を聞いてお土産を選ぶ',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
]

export const SCENARIO_DETAILS: Record<number, ScenarioDetail> = {
  1: {
    id: 1,
    name: '空港チェックイン',
    description: '空港での各場面で使える実践的なフレーズを学びます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '予約名を伝えてチェックインを開始する',
      '座席の希望（窓側・通路側）を伝える',
      '荷物の預け入れについて確認する',
    ],
    sampleDialog: 'I have a reservation under the name Suzuki. Can I have a window seat, please?',
    keyPhrases: ['be about to board', 'be supposed to check in', 'have to drop off my baggage'],
  },
  2: {
    id: 2,
    name: 'ビジネスミーティング',
    description: '会議で必要な表現とコミュニケーションスキルを身につけます',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '会議の冒頭で自分の意見を述べる',
      '他の参加者の提案に賛成・反対を表明する',
      '次のアクションアイテムを確認する',
    ],
    sampleDialog: 'From my perspective, we should prioritize the user experience over new features at this stage.',
    keyPhrases: ['want to bring up', 'need to follow up on', 'be ready to move forward'],
  },
  3: {
    id: 3,
    name: 'レストランでの注文',
    description: '飲食店での様々な場面に対応できる表現を学びます',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      'ウェイターを呼んでメニューを依頼する',
      'おすすめ料理やサイドメニューについて尋ねる',
      'アレルギーや食材の制限を伝える',
    ],
    sampleDialog: "Could you recommend something vegetarian? I'm allergic to nuts.",
    keyPhrases: ['would like to order', 'be allergic to', 'want to try'],
  },
  4: {
    id: 4,
    name: 'オンライン商談',
    description: 'リモート環境での商談に必要な表現とマナーを習得します',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    learningGoals: [
      '会議の冒頭で自己紹介とアイスブレイクを行う',
      '自社の提案内容を簡潔に説明する',
      '相手の質問に答えて懸念点を解消する',
    ],
    sampleDialog: "Let's recap the action items and confirm the next steps for both teams.",
    keyPhrases: ['would like to walk you through', 'be willing to consider', 'plan to move forward'],
  },
  5: {
    id: 5,
    name: 'ホテルチェックイン',
    description: '宿泊時に必要なコミュニケーションスキルを磨きます',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '予約名を伝えてチェックイン手続きを開始する',
      '部屋のアップグレードや追加リクエストを依頼する',
      'ホテルの設備やサービスについて質問する',
    ],
    sampleDialog: 'Is it possible to have a late checkout tomorrow around 2 PM?',
    keyPhrases: ['have a reservation under', 'would like to request', 'need to check out'],
  },
  // --- Issue #27: 追加対象シナリオ ---
  6: {
    id: 6,
    name: '最高のバケーション',
    description: '理想の休暇プランを説明しながら旅行英会話を練習します',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '行きたい旅行先とその理由を説明する',
      '滞在期間と予算の希望を伝える',
      'おすすめのアクティビティや観光地を尋ねる',
    ],
    sampleDialog: "I'd love to spend a week at a beach resort. Do you have any recommendations?",
    keyPhrases: ['dream of going to', 'would love to stay at', 'want to get away from'],
  },
  7: {
    id: 7,
    name: '日本を案内する',
    description: '海外の友人に日本の観光地や文化を英語で紹介します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '訪問したい観光地を提案して魅力を説明する',
      '移動手段（電車・バス・タクシー）と所要時間を伝える',
      '相手の興味や好みを聞いて計画を調整する',
    ],
    sampleDialog:
      "If you like history, we should definitely visit Kyoto. Would you be interested in staying there for two days?",
    keyPhrases: ['would like to show you around', 'plan to take you to', 'want to introduce you to'],
  },
  8: {
    id: 8,
    name: '入国審査・税関で',
    description: '入国審査と税関で想定される質問への対応を練習します',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 18,
    learningGoals: [
      '訪問目的（観光・ビジネス）と滞在期間を答える',
      '滞在先のホテル名と住所を伝える',
      '持ち込み品の申告や追加質問に対応する',
    ],
    sampleDialog:
      "I'm here on business for five days, and I'll be staying at the Grand Tokyo Hotel. Would you like to see my return ticket?",
    keyPhrases: ['be here on business', 'plan to stay for', 'need to declare'],
  },
  9: {
    id: 9,
    name: '旅行計画を友達と相談',
    description: '友人と旅行計画を立てながら提案・調整の英語表現を学びます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '行きたい場所と日程の候補を提案する',
      '相手の都合や希望を聞いて調整する',
      '予算とやりたいアクティビティを共有する',
    ],
    sampleDialog: "How about going to Osaka for the weekend? We could visit Universal Studios Japan.",
    keyPhrases: ['be thinking of going to', 'want to spend time doing', 'be flexible about'],
  },
  10: {
    id: 10,
    name: '財布を無くして警察に相談',
    description: '紛失状況を冷静に説明し、必要な手続きを相談します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      'いつどこで財布を無くしたかを説明する',
      '財布の色・形・中身（カード・現金）を伝える',
      '遺失物届の手続きについて確認する',
    ],
    sampleDialog:
      "I lost my wallet on the train about an hour ago. Could you tell me what I should do now?",
    keyPhrases: ['seem to have lost', 'need to report', 'try to remember'],
  },
  11: {
    id: 11,
    name: 'カスタマーサービスに相談',
    description: 'トラブルの内容を丁寧に説明し、解決策を一緒に探ります',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '商品の不具合や問題点を具体的に説明する',
      '返品・交換・返金のいずれかを依頼する',
      '担当者の提案を確認して対応を決める',
    ],
    sampleDialog:
      "I received a damaged item in my order. Could you tell me if I can get a replacement or a refund?",
    keyPhrases: ['would like to ask about', 'need to complain about', 'hope to get replaced'],
  },
  12: {
    id: 12,
    name: 'おしゃれカフェで店員と雑談',
    description: '注文に加えて店員との軽い雑談を楽しむ会話を練習します',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      'おすすめのドリンクや季節限定メニューを尋ねる',
      '店の雰囲気やインテリアについてコメントする',
      '天気や最近の出来事について軽く話す',
    ],
    sampleDialog:
      "This place has such a nice atmosphere. Do you have any seasonal drinks you recommend?",
    keyPhrases: ['feel like trying', 'be curious to know', 'keep coming back to'],
  },
  13: {
    id: 13,
    name: 'ショーチケットを入手',
    description: '日時や席種を確認しながらショーチケットを購入します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    learningGoals: [
      '希望の日時と人数を伝える',
      '座席の種類（前方・中央・後方）と価格を確認する',
      '空席がない場合は別の日時を相談する',
    ],
    sampleDialog:
      "I'd like two tickets for tonight's show around 7 PM. Are there any seats left near the front?",
    keyPhrases: ['be looking for', 'hope to get seats near', 'want to sit close to'],
  },
  14: {
    id: 14,
    name: '公園で雑談',
    description: '初対面の人と公園で軽く挨拶や雑談を交わします',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    learningGoals: [
      '天気や公園の雰囲気について話しかける',
      '相手の趣味やこの公園に来る頻度を尋ねる',
      '別れ際に「また会いましょう」と挨拶する',
    ],
    sampleDialog:
      "It's such a nice day today, isn't it? Do you often come to this park for a walk?",
    keyPhrases: ['just wanted to say', 'enjoy spending time', 'like to come here to'],
  },
  15: {
    id: 15,
    name: 'ミーティングをリスケする',
    description: '予定変更の理由を伝えつつ、代替案を丁寧に提案します',
    category: 'business',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    learningGoals: [
      '予定変更が必要な理由を簡潔に伝える',
      '代替の日時候補を2〜3つ提案する',
      '相手の都合を確認して謝罪の言葉を添える',
    ],
    sampleDialog:
      "Something urgent came up this afternoon. Would it be possible to move our meeting to tomorrow morning?",
    keyPhrases: ['need to reschedule', 'be able to move to', 'appreciate it if we could'],
  },
  16: {
    id: 16,
    name: 'ミーティングを立てる',
    description: '関係者と日程調整をしながら会議を設定する表現を学びます',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '会議の目的と所要時間を伝える',
      '複数の候補日時を提示する',
      '参加者全員の都合を確認して日程を確定する',
    ],
    sampleDialog:
      "I'd like to set up a 30-minute meeting next week. Are you available on Tuesday or Wednesday afternoon?",
    keyPhrases: ['want to set up', 'be available to meet', 'work around your schedule'],
  },
  17: {
    id: 17,
    name: '会議を進行する',
    description: '議題の提示から議論の整理まで会議進行の表現を集中的に練習します',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '会議の冒頭でアジェンダを提示する',
      '各議題で参加者の意見を引き出す',
      '決定事項とアクションアイテムを確認する',
    ],
    sampleDialog:
      "Let's move on to the second agenda item. Could you briefly share your thoughts on the proposed timeline?",
    keyPhrases: ['would like to start with', 'move on to', 'come back to'],
  },
  18: {
    id: 18,
    name: '契約条件の交渉',
    description: '条件の違いを整理しながら互いに納得できる合意点を探ります',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '価格・納期・支払い条件について確認する',
      '自社の希望条件と譲歩できる範囲を伝える',
      '相手の提案に対して代替案を提示する',
    ],
    sampleDialog:
      "If we extend the contract period, would you be open to offering a discount on the monthly fee?",
    keyPhrases: ['would like to focus on', 'be prepared to offer', 'be willing to compromise'],
  },
  19: {
    id: 19,
    name: '顧客満足度の調査結果をプレゼン',
    description: '調査結果の要点とインサイトを分かりやすく説明する練習をします',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '調査の概要（期間・対象・方法）を説明する',
      '主要な数値結果とその変化を伝える',
      '結果から導かれる改善提案を述べる',
    ],
    sampleDialog:
      "Overall satisfaction increased by 12%, mainly due to faster response times. How would you like us to act on these findings?",
    keyPhrases: ['would like to share', 'be based on', 'lead us to believe'],
  },
  20: {
    id: 20,
    name: 'プロジェクトの遅延を謝罪する',
    description: '遅延の理由と今後の対策を誠実かつ具体的に説明します',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '遅延の事実と原因を正直に説明する',
      '謝罪の言葉と責任の所在を明確にする',
      '新しいスケジュールと再発防止策を提示する',
    ],
    sampleDialog:
      "We're really sorry for the delay. A key dependency took longer than expected, but here is our updated timeline.",
    keyPhrases: ['would like to apologize for', 'have been trying to catch up', 'plan to prevent this from happening again'],
  },
  21: {
    id: 21,
    name: '体調不良で休む',
    description: '体調不良を丁寧に伝え、業務の引き継ぎを相談する場面を想定します',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
    learningGoals: [
      '体調不良の症状（熱・頭痛など）を伝える',
      '休みたい日数と復帰予定を説明する',
      '担当業務の引き継ぎ先を相談する',
    ],
    sampleDialog:
      "I'm not feeling well today and have a fever. Would it be okay if I take the day off and hand over my tasks to a colleague?",
    keyPhrases: ['not feel well today', 'need to take the day off', 'hand over my tasks'],
  },
  // --- 追加シナリオ: 日常会話 (daily) ---
  22: {
    id: 22,
    name: '病院で症状を説明',
    description: '体調不良の症状を医師に詳しく伝えます',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      'いつから症状があるか説明する',
      '痛みの種類や程度を伝える',
      'アレルギーや服用中の薬を伝える',
    ],
    sampleDialog:
      "I've been having a headache since yesterday morning. It's a sharp pain on the right side of my head.",
    keyPhrases: ['have been experiencing', 'started about ... ago', 'be allergic to'],
  },
  23: {
    id: 23,
    name: '薬局で薬を購入',
    description: '症状を伝えて適切な薬を選んでもらいます',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '症状を簡潔に伝える',
      '薬の飲み方や副作用を確認する',
      '他の薬との飲み合わせを尋ねる',
    ],
    sampleDialog:
      "I'm looking for something for a sore throat. How often should I take this medicine?",
    keyPhrases: ['be looking for something for', 'how often should I take', 'have any side effects'],
  },
  24: {
    id: 24,
    name: '歯医者で予約・相談',
    description: '歯の痛みを説明し予約を取ります',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    learningGoals: [
      '歯の痛みや問題を説明する',
      '予約の希望日時を伝える',
      '治療内容や費用を確認する',
    ],
    sampleDialog:
      "I have a toothache in the back of my mouth. Would it be possible to see the dentist this week?",
    keyPhrases: ['have a toothache', 'would like to make an appointment', 'how much will it cost'],
  },
  25: {
    id: 25,
    name: 'スーパーで店員に質問',
    description: '商品の場所や代替品について尋ねます',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '商品の場所を尋ねる',
      '代替品やおすすめを聞く',
      '賞味期限や産地を確認する',
    ],
    sampleDialog:
      "Excuse me, I'm looking for gluten-free bread. Where can I find it?",
    keyPhrases: ['be looking for', 'do you have any', 'where can I find'],
  },
  26: {
    id: 26,
    name: '服屋で試着・相談',
    description: 'サイズや色違いについて店員と話します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '試着したいことを伝える',
      '別のサイズや色を依頼する',
      '店員のおすすめを聞く',
    ],
    sampleDialog:
      "I'd like to try this on. Do you have it in a smaller size?",
    keyPhrases: ['would like to try on', 'do you have this in', 'what do you recommend'],
  },
  27: {
    id: 27,
    name: '美容院で髪型をオーダー',
    description: '希望のスタイルを具体的に伝えます',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '希望の髪型を具体的に説明する',
      'カットの長さや量を伝える',
      'スタイリングの希望を伝える',
    ],
    sampleDialog:
      "I'd like to get a trim, but I want to keep the length. Could you just take off about an inch?",
    keyPhrases: ['would like to get', 'want to keep the length', 'not too short'],
  },
  28: {
    id: 28,
    name: '携帯ショップで契約相談',
    description: 'プランの比較や手続きについて相談します',
    category: 'daily',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '現在の利用状況と希望プランを説明する',
      '料金やデータ容量を比較する',
      '契約条件や解約について確認する',
    ],
    sampleDialog:
      "I'm interested in switching to a plan with more data. What's included in the unlimited plan?",
    keyPhrases: ['be interested in switching to', "what's included in", 'are there any hidden fees'],
  },
  29: {
    id: 29,
    name: '家電量販店で相談',
    description: '製品の違いやおすすめを聞きます',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '探している製品の用途を説明する',
      '製品間の違いを質問する',
      '保証やアフターサービスを確認する',
    ],
    sampleDialog:
      "I'm looking for a laptop that's good for video editing. What's the difference between these two models?",
    keyPhrases: ['be looking for a ... that', "what's the difference between", 'does it come with a warranty'],
  },
  30: {
    id: 30,
    name: 'オンライン注文の問い合わせ',
    description: '配送状況や返品について電話で確認します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '注文番号を伝えて状況を確認する',
      '配送の遅延について尋ねる',
      '返品・交換の手続きを依頼する',
    ],
    sampleDialog:
      "I'd like to check on my order. The tracking says it was delivered, but it hasn't arrived yet.",
    keyPhrases: ['would like to check on', "hasn't arrived yet", 'would like to return'],
  },
  31: {
    id: 31,
    name: '不動産屋で部屋探し',
    description: '希望条件を伝えて物件を紹介してもらいます',
    category: 'daily',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '希望エリアと予算を伝える',
      '間取りや設備の条件を説明する',
      '内見の予約を取る',
    ],
    sampleDialog:
      "I'm looking for a one-bedroom apartment near the station, within my budget of $1,500 a month.",
    keyPhrases: ['be looking for a place', 'within my budget', 'would like to schedule a viewing'],
  },
  32: {
    id: 32,
    name: '引っ越し業者に見積もり依頼',
    description: '荷物量や日程を伝えて見積もりを取ります',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '引っ越し元と先の住所を伝える',
      '荷物の量や大型家具を説明する',
      '希望日と見積もり金額を確認する',
    ],
    sampleDialog:
      "I'd like to get a quote for moving from downtown to the suburbs. I have a sofa and a queen-size bed.",
    keyPhrases: ['would like to get a quote', 'be moving from ... to', 'how much would it cost'],
  },
  33: {
    id: 33,
    name: '修理業者を呼ぶ',
    description: '故障状況を説明し修理を依頼します',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '故障の状況を具体的に説明する',
      '修理の緊急度を伝える',
      '訪問日時と費用を確認する',
    ],
    sampleDialog:
      "I have a problem with my washing machine. It stopped working in the middle of a cycle. How soon can you come?",
    keyPhrases: ['have a problem with', 'stopped working', 'how soon can you come'],
  },
  34: {
    id: 34,
    name: '隣人に挨拶・自己紹介',
    description: '引っ越し後の挨拶と軽い会話をします',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '引っ越してきたことを伝える',
      '自分の名前と簡単な自己紹介をする',
      '近所のことについて質問する',
    ],
    sampleDialog:
      "Hi, I just moved in next door. My name is Yuki. Is there anything I should know about the building?",
    keyPhrases: ['just moved in', 'nice to meet you', 'is there anything I should know'],
  },
  35: {
    id: 35,
    name: '郵便局で荷物を送る',
    description: '送り先や配送方法を選んで発送します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '送り先と送り方を伝える',
      '届くまでの日数を確認する',
      '追跡や保険について尋ねる',
    ],
    sampleDialog:
      "I'd like to send this package to New York. How long will it take to arrive?",
    keyPhrases: ['would like to send this to', 'how long will it take', 'can I get tracking'],
  },
  36: {
    id: 36,
    name: '銀行で口座開設',
    description: '必要書類や口座種類について相談します',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '開設したい口座の種類を伝える',
      '必要書類を確認する',
      '手数料やサービスについて質問する',
    ],
    sampleDialog:
      "I'd like to open a savings account. What documents do I need to bring?",
    keyPhrases: ['would like to open an account', 'what documents do I need', 'are there any fees'],
  },
  37: {
    id: 37,
    name: '図書館で本を探す',
    description: '読みたい本を司書に相談して探します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '探している本のジャンルや著者を伝える',
      '本の場所を尋ねる',
      '貸出期間や予約方法を確認する',
    ],
    sampleDialog:
      "I'm looking for books about Japanese history. Where can I find them?",
    keyPhrases: ['be looking for books about', 'where can I find', 'how long can I borrow'],
  },
  38: {
    id: 38,
    name: '友人を食事に誘う',
    description: '予定を聞いてレストランを提案します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '食事に誘う理由やきっかけを伝える',
      '日時と場所を提案する',
      '相手の都合を確認する',
    ],
    sampleDialog:
      "Would you like to grab dinner this weekend? Are you free on Saturday evening?",
    keyPhrases: ['would you like to grab', 'are you free on', 'how about we go to'],
  },
  39: {
    id: 39,
    name: 'パーティーで初対面の人と会話',
    description: '自己紹介から共通の話題を見つけます',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '自己紹介をして相手の名前を聞く',
      '共通の知人や話題を見つける',
      '連絡先を交換する',
    ],
    sampleDialog:
      "Hi, I'm Kenji. How do you know the host? It's great to meet someone who also works in tech!",
    keyPhrases: ['how do you know', 'what do you do', 'would love to keep in touch'],
  },
  40: {
    id: 40,
    name: '習い事の体験申し込み',
    description: 'ヨガや料理教室の体験レッスンを申し込みます',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '興味のあるクラスについて質問する',
      '体験レッスンの日程を確認する',
      '料金や持ち物を尋ねる',
    ],
    sampleDialog:
      "I'm interested in trying the beginner yoga class. Do you offer trial lessons?",
    keyPhrases: ['be interested in trying', 'do you offer trial lessons', 'what do I need to bring'],
  },
  41: {
    id: 41,
    name: 'ジムに入会する',
    description: '料金プランや設備について質問して契約します',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '利用目的と希望する設備を伝える',
      '会員プランと料金を比較する',
      '入会手続きと利用ルールを確認する',
    ],
    sampleDialog:
      "I'm looking to join a gym with a pool. What's included in the membership?",
    keyPhrases: ['be looking to join', "what's included in the membership", 'are there any contracts'],
  },
  // --- 追加シナリオ: 旅行 (travel) ---
  42: {
    id: 42,
    name: '機内でCAにリクエスト',
    description: '飲み物や毛布を頼む、座席変更を相談します',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '飲み物や食事をリクエストする',
      'ブランケットやヘッドフォンを依頼する',
      '座席や通路の問題を相談する',
    ],
    sampleDialog:
      "Excuse me, could I have a blanket? Also, would it be possible to move to an aisle seat?",
    keyPhrases: ['could I have', 'would it be possible to', 'is there any way to'],
  },
  43: {
    id: 43,
    name: '乗り継ぎ便を確認',
    description: '遅延時の対応やゲート変更を確認します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    learningGoals: [
      '乗り継ぎゲートと時間を確認する',
      '遅延時の対応を尋ねる',
      '荷物の受け取りについて確認する',
    ],
    sampleDialog:
      "I have a connecting flight to Paris. Will I make my connection if we're delayed?",
    keyPhrases: ['have a connecting flight to', 'will I make my connection', 'do I need to pick up my luggage'],
  },
  44: {
    id: 44,
    name: '荷物が届かない！',
    description: 'ロストバゲージの状況説明と対応依頼をします',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '荷物が届いていない状況を説明する',
      '荷物の特徴を詳しく伝える',
      '補償や配送手配について交渉する',
    ],
    sampleDialog:
      "My luggage didn't arrive on the carousel. It's a large black suitcase with a red tag. What compensation can I get?",
    keyPhrases: ["my luggage didn't arrive", "it's a ... colored suitcase", 'what compensation can I get'],
  },
  45: {
    id: 45,
    name: '空港でフライト変更',
    description: '予約変更やキャンセルの手続きをします',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '変更したい理由と希望を伝える',
      '代替便のオプションを確認する',
      '追加料金や条件を交渉する',
    ],
    sampleDialog:
      "I need to change my flight due to a family emergency. Are there any available flights tonight?",
    keyPhrases: ['need to change my flight', 'are there any available flights', 'will there be any additional charges'],
  },
  46: {
    id: 46,
    name: 'レンタカーを借りる',
    description: '車種選択、保険、返却方法を確認します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '希望の車種と期間を伝える',
      '保険オプションを確認する',
      '返却場所と燃料ルールを確認する',
    ],
    sampleDialog:
      "I'd like to rent a compact car for three days. What insurance options do you have?",
    keyPhrases: ['would like to rent a', 'what insurance options do you have', 'where do I return the car'],
  },
  47: {
    id: 47,
    name: '電車・バスのチケット購入',
    description: '行き先と時間を伝えてチケットを買います',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '行き先と人数を伝える',
      '片道か往復かを指定する',
      '出発時間とプラットフォームを確認する',
    ],
    sampleDialog:
      "I'd like two round-trip tickets to Oxford, please. Which platform does it leave from?",
    keyPhrases: ['would like a ticket to', 'one way or round trip', 'which platform does it leave from'],
  },
  48: {
    id: 48,
    name: 'ホテルの部屋に問題発生',
    description: 'エアコン故障や清掃不備を報告します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '問題の内容を具体的に説明する',
      '対応や部屋の変更を依頼する',
      '補償について確認する',
    ],
    sampleDialog:
      "There's a problem with the air conditioning in my room. It's not working at all. Could I change rooms?",
    keyPhrases: ["there's a problem with", 'would it be possible to change rooms', 'can I get a discount'],
  },
  49: {
    id: 49,
    name: 'ルームサービスを注文',
    description: 'メニューを見て電話で注文します',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      'メニューから注文したいものを伝える',
      'アレルギーや好みを伝える',
      '届け時間と支払い方法を確認する',
    ],
    sampleDialog:
      "I'd like to order the club sandwich, please. Could you leave out the tomatoes? How long will it take?",
    keyPhrases: ['would like to order', 'could you leave out the', 'how long will it take'],
  },
  50: {
    id: 50,
    name: 'レイトチェックアウトを交渉',
    description: '延長料金や空き状況を確認して依頼します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    learningGoals: [
      '延長したい理由と時間を伝える',
      '追加料金を確認する',
      '荷物預かりの代替案を相談する',
    ],
    sampleDialog:
      "My flight isn't until 6 PM. Would it be possible to check out at 2 PM instead of noon?",
    keyPhrases: ['would it be possible to check out later', 'is there an extra charge', 'could you hold my luggage'],
  },
  51: {
    id: 51,
    name: 'Airbnbホストとやりとり',
    description: 'チェックイン方法や設備について質問します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      'チェックイン方法を確認する',
      '設備や周辺情報について質問する',
      'トラブル時の連絡方法を確認する',
    ],
    sampleDialog:
      "Hi! How do I get into the apartment? Is there WiFi available? How can I reach you if there's a problem?",
    keyPhrases: ['how do I get into', 'is there ... available', 'how can I reach you if'],
  },
  52: {
    id: 52,
    name: '観光案内所で情報収集',
    description: 'おすすめスポットやアクセスを聞きます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      'おすすめの観光スポットを尋ねる',
      'アクセス方法と所要時間を確認する',
      '地図やパンフレットをもらう',
    ],
    sampleDialog:
      "What do you recommend for first-time visitors? How do I get to the old town from here?",
    keyPhrases: ['what do you recommend', 'how do I get to', 'do you have a map'],
  },
  53: {
    id: 53,
    name: '現地ツアーに申し込む',
    description: 'ツアー内容を確認して予約します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      'ツアーの内容と所要時間を確認する',
      '集合場所と持ち物を尋ねる',
      'キャンセルポリシーを確認する',
    ],
    sampleDialog:
      "What does the city tour include? Where do we meet, and what's your cancellation policy?",
    keyPhrases: ['what does the tour include', 'where do we meet', "what's your cancellation policy"],
  },
  54: {
    id: 54,
    name: '美術館・博物館で質問',
    description: '展示物や音声ガイドについて尋ねます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      'チケットの種類と料金を確認する',
      '音声ガイドやツアーについて尋ねる',
      '特定の展示物の場所を聞く',
    ],
    sampleDialog:
      "How much is admission for adults? Do you have audio guides in Japanese?",
    keyPhrases: ['how much is admission', 'do you have audio guides', 'where can I find'],
  },
  55: {
    id: 55,
    name: '写真を撮ってもらう',
    description: '通行人にお願いして撮影してもらいます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    learningGoals: [
      '丁寧に撮影をお願いする',
      '撮り方の希望を伝える',
      'お礼を言って会話を締めくくる',
    ],
    sampleDialog:
      "Excuse me, would you mind taking a photo of us? Could you get the tower in the background?",
    keyPhrases: ['would you mind taking', 'could you get ... in the background', 'thank you so much'],
  },
  56: {
    id: 56,
    name: '現地の人におすすめを聞く',
    description: 'レストランや穴場スポットを教えてもらいます',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    learningGoals: [
      '地元で人気の場所を尋ねる',
      '予算や好みを伝える',
      '行き方や営業時間を確認する',
    ],
    sampleDialog:
      "Do you know any good local restaurants around here? What would you recommend for seafood?",
    keyPhrases: ['do you know any good', 'what would you recommend for', 'how do I get there'],
  },
  57: {
    id: 57,
    name: '道に迷って助けを求める',
    description: '地図を見せながら行き方を聞きます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      '目的地を伝えて道を尋ねる',
      '道順を確認・復唱する',
      '目印やランドマークを聞く',
    ],
    sampleDialog:
      "Excuse me, I'm trying to get to the central station. Could you point me in the right direction?",
    keyPhrases: ['trying to get to', 'could you point me in the direction', 'is it far from here'],
  },
  58: {
    id: 58,
    name: '体調不良で現地の病院へ',
    description: '症状を説明し保険書類を提示します',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '症状と発症時期を説明する',
      '保険証や旅行保険を提示する',
      '処方箋や診断書について確認する',
    ],
    sampleDialog:
      "I've been feeling dizzy since this morning. I have travel insurance. Can I get a medical certificate?",
    keyPhrases: ['have been feeling ... since', 'have travel insurance', 'can I get a medical certificate'],
  },
  59: {
    id: 59,
    name: 'パスポート紛失の対応',
    description: '大使館への連絡と再発行手続きをします',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '紛失状況を説明する',
      '再発行の手続きを確認する',
      '一時渡航書について相談する',
    ],
    sampleDialog:
      "I've lost my passport. What do I need to do to get a replacement? How long will it take?",
    keyPhrases: ['lost my passport', 'what do I need to do to get a replacement', 'how long will it take'],
  },
  60: {
    id: 60,
    name: '両替所で両替',
    description: 'レートを確認して両替を依頼します',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    learningGoals: [
      '両替したい金額と通貨を伝える',
      'レートと手数料を確認する',
      '紙幣の種類を指定する',
    ],
    sampleDialog:
      "I'd like to exchange 500 dollars to euros. What's the exchange rate today?",
    keyPhrases: ['would like to exchange', "what's the exchange rate", 'could I have it in smaller bills'],
  },
  61: {
    id: 61,
    name: 'お土産屋で買い物',
    description: '商品の説明を聞いてお土産を選びます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      'おすすめのお土産を尋ねる',
      '値段や素材について質問する',
      'ギフト包装を依頼する',
    ],
    sampleDialog:
      "What's popular as a souvenir from here? Is this made locally? Could you wrap it as a gift?",
    keyPhrases: ["what's popular as a souvenir", 'is this made locally', 'could you wrap it as a gift'],
  },
}

export const getScenarioDetail = (id: number): ScenarioDetail | null => {
  return SCENARIO_DETAILS[id] ?? null
}

