import { ScenarioDetail, ScenarioSummary } from '@/types/scenario'

export const SCENARIO_CATEGORIES = [
  {
    id: 'travel',
    label: '旅行',
    description: '空港・ホテル・移動など旅行時の会話を想定',
  },
  {
    id: 'business',
    label: 'ビジネス',
    description: 'ミーティング・商談・メール対応など',
  },
  {
    id: 'daily',
    label: '日常会話',
    description: '日常生活でよく使う会話を中心に',
  },
]

export const SCENARIO_LIST: ScenarioSummary[] = [
  {
    id: 1,
    name: '空港チェックイン',
    description: 'チェックインから搭乗までの一連の流れを練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 2,
    name: 'ビジネスミーティング',
    description: '会議での発言や合意形成に必要な表現を学習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 3,
    name: 'レストランでの注文',
    description: '予約から注文、会計までの会話パターンを習得',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 4,
    name: 'オンライン商談',
    description: 'リモートミーティングでの説明や質問に対応',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 30,
  },
  {
    id: 5,
    name: 'ホテルチェックイン',
    description: '予約確認から要望の伝え方までを網羅',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  // --- Issue #27: 追加対象シナリオ ---
  // travel
  {
    id: 6,
    name: '最高のバケーション',
    description: '理想の休暇プランを説明しながら旅行英会話を練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 7,
    name: '日本を案内する',
    description: '海外の友人に日本の観光地や文化を英語で紹介',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 8,
    name: '入国審査・税関で',
    description: '入国審査と税関のやり取りを想定した実践的な会話',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 18,
  },
  {
    id: 9,
    name: '旅行計画を友達と相談',
    description: '友人と旅行計画を立てながら提案・調整の表現を学ぶ',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  // daily
  {
    id: 10,
    name: '財布を無くして警察に相談',
    description: 'トラブル時に状況を説明して助けを求める表現を練習',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 11,
    name: 'カスタマーサービスに相談',
    description: '商品の不具合やトラブルをカスタマーサービスに伝える',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 12,
    name: 'おしゃれカフェで店員と雑談',
    description: '注文に加えて軽い雑談を交えたカジュアルな会話',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 13,
    name: 'ショーチケットを入手',
    description: 'チケットの種類や席を確認しながら購入する会話',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  },
  {
    id: 14,
    name: '公園で雑談',
    description: '初対面の人と趣味や天気について気軽に話す練習',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  },
  // business
  {
    id: 15,
    name: 'ミーティングをリスケする',
    description: '予定変更の依頼と代替案の提案を丁寧に伝える',
    category: 'business',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  },
  {
    id: 16,
    name: 'ミーティングを立てる',
    description: '関係者に日程候補を提示しながら会議を設定する',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 17,
    name: '会議を進行する',
    description: '議題の提示から議論の整理まで会議進行の英語表現',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 18,
    name: '契約条件の交渉',
    description: '価格や条件の違いを整理しながら合意点を探る',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 19,
    name: '顧客満足度の調査結果をプレゼン',
    description: '調査結果を分かりやすく説明し示唆を伝えるプレゼン',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 20,
    name: 'プロジェクトの遅延を謝罪する',
    description: '遅延の理由と今後の対策を誠実に説明する表現を練習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 21,
    name: '体調不良で休む',
    description: '体調不良を丁寧に伝え、代替対応を相談する会話',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
  },
]

export const SCENARIO_DETAILS: Record<number, ScenarioDetail> = {
  1: {
    id: 1,
    name: '空港チェックイン',
    description: '空港での各場面で使える実践的なフレーズを学びます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '旅の始まりに必要な表現を定着させる',
      'チェックイン時のやりとりに自信を持つ',
      '予期せぬ質問にも対応できる力をつける',
    ],
    sampleDialog: 'I have a reservation under the name Suzuki. Can I have a window seat, please?',
    keyPhrases: ['be about to board', 'be supposed to check in', 'have to drop off my baggage'],
  },
  2: {
    id: 2,
    name: 'ビジネスミーティング',
    description: '会議で必要な表現とコミュニケーションスキルを身につけます',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '意見を明確に述べる表現を習得',
      '合意形成のためのフレーズを練習',
      '質問に対する対応力を強化',
    ],
    sampleDialog: 'From my perspective, we should prioritize the user experience over new features at this stage.',
    keyPhrases: ['want to bring up', 'need to follow up on', 'be ready to move forward'],
  },
  3: {
    id: 3,
    name: 'レストランでの注文',
    description: '飲食店での様々な場面に対応できる表現を学びます',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      'メニューを理解し適切に注文する力をつける',
      'アレルギーや好みの説明に慣れる',
      '会計時のやり取りをスムーズに行う',
    ],
    sampleDialog: 'Could you recommend something vegetarian? I’m allergic to nuts.',
    keyPhrases: ['would like to order', 'be allergic to', 'want to try'],
  },
  4: {
    id: 4,
    name: 'オンライン商談',
    description: 'リモート環境での商談に必要な表現とマナーを習得します',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    learningGoals: [
      'オンラインでの自己紹介とアイスブレイクに慣れる',
      '提案内容を説得力を持って伝える',
      'フォローアップとアクションアイテムを明確にする',
    ],
    sampleDialog: 'Let’s recap the action items and confirm the next steps for both teams.',
    keyPhrases: ['would like to walk you through', 'be willing to consider', 'plan to move forward'],
  },
  5: {
    id: 5,
    name: 'ホテルチェックイン',
    description: '宿泊時に必要なコミュニケーションスキルを磨きます',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '予約内容の確認と要望の伝え方を練習',
      'トラブル対応時の英語表現に慣れる',
      'チェックアウト時の手続きをスムーズにする',
    ],
    sampleDialog: 'Is it possible to have a late checkout tomorrow around 2 PM?',
    keyPhrases: ['have a reservation under', 'would like to request', 'need to check out'],
  },
  // --- Issue #27: 追加対象シナリオ ---
  6: {
    id: 6,
    name: '最高のバケーション',
    description: '理想の休暇プランを説明しながら旅行英会話を練習します',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '休暇の予定や希望を英語で説明する',
      '場所・期間・予算などの基本情報を整理して伝える',
      '相手の質問に答えながら会話を広げる',
    ],
    sampleDialog: "I'd love to spend a week at a beach resort. Do you have any recommendations?",
    keyPhrases: ['dream of going to', 'would love to stay at', 'want to get away from'],
  },
  7: {
    id: 7,
    name: '日本を案内する',
    description: '海外の友人に日本の観光地や文化を英語で紹介します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '観光地や名物を分かりやすく説明する',
      '移動手段や所要時間を伝える表現を身につける',
      '相手の興味に合わせて提案をアレンジする',
    ],
    sampleDialog:
      "If you like history, we should definitely visit Kyoto. Would you be interested in staying there for two days?",
    keyPhrases: ['would like to show you around', 'plan to take you to', 'want to introduce you to'],
  },
  8: {
    id: 8,
    name: '入国審査・税関で',
    description: '入国審査と税関で想定される質問への対応を練習します',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 18,
    learningGoals: [
      '入国目的や滞在予定を明確に説明する',
      '持ち込み品や申告内容について正確に答える',
      '追加質問にも落ち着いて対応できるようにする',
    ],
    sampleDialog:
      "I'm here on business for five days, and I'll be staying at the Grand Tokyo Hotel. Would you like to see my return ticket?",
    keyPhrases: ['be here on business', 'plan to stay for', 'need to declare'],
  },
  9: {
    id: 9,
    name: '旅行計画を友達と相談',
    description: '友人と旅行計画を立てながら提案・調整の英語表現を学びます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '行き先や日程の希望を伝える',
      '相手の都合を聞きながら予定を調整する',
      '予算やアクティビティの希望を共有する',
    ],
    sampleDialog: "How about going to Osaka for the weekend? We could visit Universal Studios Japan.",
    keyPhrases: ['be thinking of going to', 'want to spend time doing', 'be flexible about'],
  },
  10: {
    id: 10,
    name: '財布を無くして警察に相談',
    description: '紛失状況を冷静に説明し、必要な手続きを相談します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '時間・場所・状況を整理して説明する',
      '財布の特徴や中身を具体的に伝える',
      '必要な書類や今後の流れを確認する',
    ],
    sampleDialog:
      "I lost my wallet on the train about an hour ago. Could you tell me what I should do now?",
    keyPhrases: ['seem to have lost', 'need to report', 'try to remember'],
  },
  11: {
    id: 11,
    name: 'カスタマーサービスに相談',
    description: 'トラブルの内容を丁寧に説明し、解決策を一緒に探ります',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '問題の内容と影響をシンプルに説明する',
      '相手の提案を確認しながら選択肢を理解する',
      '丁寧なクレーム・相談の表現に慣れる',
    ],
    sampleDialog:
      "I received a damaged item in my order. Could you tell me if I can get a replacement or a refund?",
    keyPhrases: ['would like to ask about', 'need to complain about', 'hope to get replaced'],
  },
  12: {
    id: 12,
    name: 'おしゃれカフェで店員と雑談',
    description: '注文に加えて店員との軽い雑談を楽しむ会話を練習します',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '飲み物や食事の好みを自然に伝える',
      '天気や趣味などの軽い話題で会話を続ける',
      '相手のコメントに返しながら雑談を広げる',
    ],
    sampleDialog:
      "This place has such a nice atmosphere. Do you have any seasonal drinks you recommend?",
    keyPhrases: ['feel like trying', 'be curious to know', 'keep coming back to'],
  },
  13: {
    id: 13,
    name: 'ショーチケットを入手',
    description: '日時や席種を確認しながらショーチケットを購入します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    learningGoals: [
      '希望の日時や人数を正確に伝える',
      '席の種類や価格を確認する表現を学ぶ',
      '空き状況に応じて代替案を相談する',
    ],
    sampleDialog:
      "I'd like two tickets for tonight's show around 7 PM. Are there any seats left near the front?",
    keyPhrases: ['be looking for', 'hope to get seats near', 'want to sit close to'],
  },
  14: {
    id: 14,
    name: '公園で雑談',
    description: '初対面の人と公園で軽く挨拶や雑談を交わします',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    learningGoals: [
      '自然な挨拶と自己紹介のフレーズを身につける',
      '天気や趣味など無難な話題で会話を続ける',
      '別れ際の丁寧な表現に慣れる',
    ],
    sampleDialog:
      "It's such a nice day today, isn't it? Do you often come to this park for a walk?",
    keyPhrases: ['just wanted to say', 'enjoy spending time', 'like to come here to'],
  },
  15: {
    id: 15,
    name: 'ミーティングをリスケする',
    description: '予定変更の理由を伝えつつ、代替案を丁寧に提案します',
    category: 'business',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    learningGoals: [
      '予定変更の理由をシンプルに説明する',
      '代わりの日時候補を分かりやすく提示する',
      '相手への配慮を示す表現を練習する',
    ],
    sampleDialog:
      "Something urgent came up this afternoon. Would it be possible to move our meeting to tomorrow morning?",
    keyPhrases: ['need to reschedule', 'be able to move to', 'appreciate it if we could'],
  },
  16: {
    id: 16,
    name: 'ミーティングを立てる',
    description: '関係者と日程調整をしながら会議を設定する表現を学びます',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '会議の目的と所要時間を簡潔に説明する',
      '複数の候補日時を提示して調整する',
      '参加者の都合を確認しながら決定する',
    ],
    sampleDialog:
      "I'd like to set up a 30-minute meeting next week. Are you available on Tuesday or Wednesday afternoon?",
    keyPhrases: ['want to set up', 'be available to meet', 'work around your schedule'],
  },
  17: {
    id: 17,
    name: '会議を進行する',
    description: '議題の提示から議論の整理まで会議進行の表現を集中的に練習します',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      'アジェンダの提示と時間管理の表現を身につける',
      '意見を引き出しつつ議論を整理する',
      '決定事項とアクションアイテムを明確にまとめる',
    ],
    sampleDialog:
      "Let’s move on to the second agenda item. Could you briefly share your thoughts on the proposed timeline?",
    keyPhrases: ['would like to start with', 'move on to', 'come back to'],
  },
  18: {
    id: 18,
    name: '契約条件の交渉',
    description: '条件の違いを整理しながら互いに納得できる合意点を探ります',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '価格や納期などの条件を明確に比較する',
      '譲歩や代替案を提示する表現を身につける',
      '合意に向けて論点を整理しながら交渉する',
    ],
    sampleDialog:
      "If we extend the contract period, would you be open to offering a discount on the monthly fee?",
    keyPhrases: ['would like to focus on', 'be prepared to offer', 'be willing to compromise'],
  },
  19: {
    id: 19,
    name: '顧客満足度の調査結果をプレゼン',
    description: '調査結果の要点とインサイトを分かりやすく説明する練習をします',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      'グラフや数値を言葉で説明する',
      '調査結果から導かれる示唆を整理して伝える',
      '次のアクション案を論理的に提案する',
    ],
    sampleDialog:
      "Overall satisfaction increased by 12%, mainly due to faster response times. How would you like us to act on these findings?",
    keyPhrases: ['would like to share', 'be based on', 'lead us to believe'],
  },
  20: {
    id: 20,
    name: 'プロジェクトの遅延を謝罪する',
    description: '遅延の理由と今後の対策を誠実かつ具体的に説明します',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '状況と原因を事実ベースで整理して伝える',
      '謝罪と責任の取り方を適切に表現する',
      'リカバリープランや新しいスケジュールを共有する',
    ],
    sampleDialog:
      "We’re really sorry for the delay. A key dependency took longer than expected, but here is our updated timeline.",
    keyPhrases: ['would like to apologize for', 'have been trying to catch up', 'plan to prevent this from happening again'],
  },
  21: {
    id: 21,
    name: '体調不良で休む',
    description: '体調不良を丁寧に伝え、業務の引き継ぎを相談する場面を想定します',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
    learningGoals: [
      '症状と状況を簡潔に説明する',
      '休暇の希望日と期間を伝える',
      '担当タスクの引き継ぎ方法を相談する',
    ],
    sampleDialog:
      "I’m not feeling well today and have a fever. Would it be okay if I take the day off and hand over my tasks to a colleague?",
    keyPhrases: ['not feel well today', 'need to take the day off', 'hand over my tasks'],
  },
}

export const getScenarioDetail = (id: number): ScenarioDetail | null => {
  return SCENARIO_DETAILS[id] ?? null
}

