import { ScenarioDetail, ScenarioSummary } from '@/types/scenario'

export const SCENARIO_CATEGORIES = [
  {
    id: 'travel',
    label: '旅行',
    description: '空港・ホテル・移動など旅行時の会話を想定',
  },
  {
    id: 'business',
    label: 'ビジネス',
    description: 'ミーティング・商談・メール対応など',
  },
  {
    id: 'daily',
    label: '日常会話',
    description: '日常生活でよく使う会話を中心に',
  },
]

export const SCENARIO_LIST: ScenarioSummary[] = [
  {
    id: 1,
    name: '空港チェックイン',
    description: 'チェックインから搭乗までの一連の流れを練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 2,
    name: 'ビジネスミーティング',
    description: '会議での発言や合意形成に必要な表現を学習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 3,
    name: 'レストランでの注文',
    description: '予約から注文、会計までの会話パターンを習得',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
  },
  {
    id: 4,
    name: 'オンライン商談',
    description: 'リモートミーティングでの説明や質問に対応',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 30,
  },
  {
    id: 5,
    name: 'ホテルチェックイン',
    description: '予約確認から要望の伝え方までを網羅',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  // --- Issue #27: 追加対象シナリオ ---
  // travel
  {
    id: 6,
    name: '最高のバケーション',
    description: '理想の休暇プランを説明しながら旅行英会話を練習',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 7,
    name: '日本を案内する',
    description: '海外の友人に日本の観光地や文化を英語で紹介',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 8,
    name: '入国審査・税関で',
    description: '入国審査と税関のやり取りを想定した実践的な会話',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 18,
  },
  {
    id: 9,
    name: '旅行計画を友達と相談',
    description: '友人と旅行計画を立てながら提案・調整の表現を学ぶ',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  // daily
  {
    id: 10,
    name: '財布を無くして警察に相談',
    description: 'トラブル時に状況を説明して助けを求める表現を練習',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 11,
    name: 'カスタマーサービスに相談',
    description: '商品の不具合やトラブルをカスタマーサービスに伝える',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
  },
  {
    id: 12,
    name: 'おしゃれカフェで店員と雑談',
    description: '注文に加えて軽い雑談を交えたカジュアルな会話',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 13,
    name: 'ショーチケットを入手',
    description: 'チケットの種類や席を確認しながら購入する会話',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  },
  {
    id: 14,
    name: '公園で雑談',
    description: '初対面の人と趣味や天気について気軽に話す練習',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
  },
  // business
  {
    id: 15,
    name: 'ミーティングをリスケする',
    description: '予定変更の依頼と代替案の提案を丁寧に伝える',
    category: 'business',
    difficulty: 'beginner',
    estimatedMinutes: 15,
  },
  {
    id: 16,
    name: 'ミーティングを立てる',
    description: '関係者に日程候補を提示しながら会議を設定する',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 17,
    name: '会議を進行する',
    description: '議題の提示から議論の整理まで会議進行の英語表現',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 18,
    name: '契約条件の交渉',
    description: '価格や条件の違いを整理しながら合意点を探る',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 19,
    name: '顧客満足度の調査結果をプレゼン',
    description: '調査結果を分かりやすく説明し示唆を伝えるプレゼン',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
  },
  {
    id: 20,
    name: 'プロジェクトの遅延を謝罪する',
    description: '遅延の理由と今後の対策を誠実に説明する表現を練習',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
  },
  {
    id: 21,
    name: '体調不良で休む',
    description: '体調不良を丁寧に伝え、代替対応を相談する会話',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
  },
]

export const SCENARIO_DETAILS: Record<number, ScenarioDetail> = {
  1: {
    id: 1,
    name: '空港チェックイン',
    description: '空港での各場面で使える実践的なフレーズを学びます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '予約名を伝えてチェックインを開始する',
      '座席の希望（窓側・通路側）を伝える',
      '荷物の預け入れについて確認する',
    ],
    sampleDialog: 'I have a reservation under the name Suzuki. Can I have a window seat, please?',
    keyPhrases: ['be about to board', 'be supposed to check in', 'have to drop off my baggage'],
  },
  2: {
    id: 2,
    name: 'ビジネスミーティング',
    description: '会議で必要な表現とコミュニケーションスキルを身につけます',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '会議の冒頭で自分の意見を述べる',
      '他の参加者の提案に賛成・反対を表明する',
      '次のアクションアイテムを確認する',
    ],
    sampleDialog: 'From my perspective, we should prioritize the user experience over new features at this stage.',
    keyPhrases: ['want to bring up', 'need to follow up on', 'be ready to move forward'],
  },
  3: {
    id: 3,
    name: 'レストランでの注文',
    description: '飲食店での様々な場面に対応できる表現を学びます',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    learningGoals: [
      'ウェイターを呼んでメニューを依頼する',
      'おすすめ料理やサイドメニューについて尋ねる',
      'アレルギーや食材の制限を伝える',
    ],
    sampleDialog: "Could you recommend something vegetarian? I'm allergic to nuts.",
    keyPhrases: ['would like to order', 'be allergic to', 'want to try'],
  },
  4: {
    id: 4,
    name: 'オンライン商談',
    description: 'リモート環境での商談に必要な表現とマナーを習得します',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    learningGoals: [
      '会議の冒頭で自己紹介とアイスブレイクを行う',
      '自社の提案内容を簡潔に説明する',
      '相手の質問に答えて懸念点を解消する',
    ],
    sampleDialog: "Let's recap the action items and confirm the next steps for both teams.",
    keyPhrases: ['would like to walk you through', 'be willing to consider', 'plan to move forward'],
  },
  5: {
    id: 5,
    name: 'ホテルチェックイン',
    description: '宿泊時に必要なコミュニケーションスキルを磨きます',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '予約名を伝えてチェックイン手続きを開始する',
      '部屋のアップグレードや追加リクエストを依頼する',
      'ホテルの設備やサービスについて質問する',
    ],
    sampleDialog: 'Is it possible to have a late checkout tomorrow around 2 PM?',
    keyPhrases: ['have a reservation under', 'would like to request', 'need to check out'],
  },
  // --- Issue #27: 追加対象シナリオ ---
  6: {
    id: 6,
    name: '最高のバケーション',
    description: '理想の休暇プランを説明しながら旅行英会話を練習します',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '行きたい旅行先とその理由を説明する',
      '滞在期間と予算の希望を伝える',
      'おすすめのアクティビティや観光地を尋ねる',
    ],
    sampleDialog: "I'd love to spend a week at a beach resort. Do you have any recommendations?",
    keyPhrases: ['dream of going to', 'would love to stay at', 'want to get away from'],
  },
  7: {
    id: 7,
    name: '日本を案内する',
    description: '海外の友人に日本の観光地や文化を英語で紹介します',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '訪問したい観光地を提案して魅力を説明する',
      '移動手段（電車・バス・タクシー）と所要時間を伝える',
      '相手の興味や好みを聞いて計画を調整する',
    ],
    sampleDialog:
      "If you like history, we should definitely visit Kyoto. Would you be interested in staying there for two days?",
    keyPhrases: ['would like to show you around', 'plan to take you to', 'want to introduce you to'],
  },
  8: {
    id: 8,
    name: '入国審査・税関で',
    description: '入国審査と税関で想定される質問への対応を練習します',
    category: 'travel',
    difficulty: 'advanced',
    estimatedMinutes: 18,
    learningGoals: [
      '訪問目的（観光・ビジネス）と滞在期間を答える',
      '滞在先のホテル名と住所を伝える',
      '持ち込み品の申告や追加質問に対応する',
    ],
    sampleDialog:
      "I'm here on business for five days, and I'll be staying at the Grand Tokyo Hotel. Would you like to see my return ticket?",
    keyPhrases: ['be here on business', 'plan to stay for', 'need to declare'],
  },
  9: {
    id: 9,
    name: '旅行計画を友達と相談',
    description: '友人と旅行計画を立てながら提案・調整の英語表現を学びます',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '行きたい場所と日程の候補を提案する',
      '相手の都合や希望を聞いて調整する',
      '予算とやりたいアクティビティを共有する',
    ],
    sampleDialog: "How about going to Osaka for the weekend? We could visit Universal Studios Japan.",
    keyPhrases: ['be thinking of going to', 'want to spend time doing', 'be flexible about'],
  },
  10: {
    id: 10,
    name: '財布を無くして警察に相談',
    description: '紛失状況を冷静に説明し、必要な手続きを相談します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      'いつどこで財布を無くしたかを説明する',
      '財布の色・形・中身（カード・現金）を伝える',
      '遺失物届の手続きについて確認する',
    ],
    sampleDialog:
      "I lost my wallet on the train about an hour ago. Could you tell me what I should do now?",
    keyPhrases: ['seem to have lost', 'need to report', 'try to remember'],
  },
  11: {
    id: 11,
    name: 'カスタマーサービスに相談',
    description: 'トラブルの内容を丁寧に説明し、解決策を一緒に探ります',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    learningGoals: [
      '商品の不具合や問題点を具体的に説明する',
      '返品・交換・返金のいずれかを依頼する',
      '担当者の提案を確認して対応を決める',
    ],
    sampleDialog:
      "I received a damaged item in my order. Could you tell me if I can get a replacement or a refund?",
    keyPhrases: ['would like to ask about', 'need to complain about', 'hope to get replaced'],
  },
  12: {
    id: 12,
    name: 'おしゃれカフェで店員と雑談',
    description: '注文に加えて店員との軽い雑談を楽しむ会話を練習します',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      'おすすめのドリンクや季節限定メニューを尋ねる',
      '店の雰囲気やインテリアについてコメントする',
      '天気や最近の出来事について軽く話す',
    ],
    sampleDialog:
      "This place has such a nice atmosphere. Do you have any seasonal drinks you recommend?",
    keyPhrases: ['feel like trying', 'be curious to know', 'keep coming back to'],
  },
  13: {
    id: 13,
    name: 'ショーチケットを入手',
    description: '日時や席種を確認しながらショーチケットを購入します',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    learningGoals: [
      '希望の日時と人数を伝える',
      '座席の種類（前方・中央・後方）と価格を確認する',
      '空席がない場合は別の日時を相談する',
    ],
    sampleDialog:
      "I'd like two tickets for tonight's show around 7 PM. Are there any seats left near the front?",
    keyPhrases: ['be looking for', 'hope to get seats near', 'want to sit close to'],
  },
  14: {
    id: 14,
    name: '公園で雑談',
    description: '初対面の人と公園で軽く挨拶や雑談を交わします',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    learningGoals: [
      '天気や公園の雰囲気について話しかける',
      '相手の趣味やこの公園に来る頻度を尋ねる',
      '別れ際に「また会いましょう」と挨拶する',
    ],
    sampleDialog:
      "It's such a nice day today, isn't it? Do you often come to this park for a walk?",
    keyPhrases: ['just wanted to say', 'enjoy spending time', 'like to come here to'],
  },
  15: {
    id: 15,
    name: 'ミーティングをリスケする',
    description: '予定変更の理由を伝えつつ、代替案を丁寧に提案します',
    category: 'business',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    learningGoals: [
      '予定変更が必要な理由を簡潔に伝える',
      '代替の日時候補を2〜3つ提案する',
      '相手の都合を確認して謝罪の言葉を添える',
    ],
    sampleDialog:
      "Something urgent came up this afternoon. Would it be possible to move our meeting to tomorrow morning?",
    keyPhrases: ['need to reschedule', 'be able to move to', 'appreciate it if we could'],
  },
  16: {
    id: 16,
    name: 'ミーティングを立てる',
    description: '関係者と日程調整をしながら会議を設定する表現を学びます',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '会議の目的と所要時間を伝える',
      '複数の候補日時を提示する',
      '参加者全員の都合を確認して日程を確定する',
    ],
    sampleDialog:
      "I'd like to set up a 30-minute meeting next week. Are you available on Tuesday or Wednesday afternoon?",
    keyPhrases: ['want to set up', 'be available to meet', 'work around your schedule'],
  },
  17: {
    id: 17,
    name: '会議を進行する',
    description: '議題の提示から議論の整理まで会議進行の表現を集中的に練習します',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '会議の冒頭でアジェンダを提示する',
      '各議題で参加者の意見を引き出す',
      '決定事項とアクションアイテムを確認する',
    ],
    sampleDialog:
      "Let's move on to the second agenda item. Could you briefly share your thoughts on the proposed timeline?",
    keyPhrases: ['would like to start with', 'move on to', 'come back to'],
  },
  18: {
    id: 18,
    name: '契約条件の交渉',
    description: '条件の違いを整理しながら互いに納得できる合意点を探ります',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '価格・納期・支払い条件について確認する',
      '自社の希望条件と譲歩できる範囲を伝える',
      '相手の提案に対して代替案を提示する',
    ],
    sampleDialog:
      "If we extend the contract period, would you be open to offering a discount on the monthly fee?",
    keyPhrases: ['would like to focus on', 'be prepared to offer', 'be willing to compromise'],
  },
  19: {
    id: 19,
    name: '顧客満足度の調査結果をプレゼン',
    description: '調査結果の要点とインサイトを分かりやすく説明する練習をします',
    category: 'business',
    difficulty: 'advanced',
    estimatedMinutes: 24,
    learningGoals: [
      '調査の概要（期間・対象・方法）を説明する',
      '主要な数値結果とその変化を伝える',
      '結果から導かれる改善提案を述べる',
    ],
    sampleDialog:
      "Overall satisfaction increased by 12%, mainly due to faster response times. How would you like us to act on these findings?",
    keyPhrases: ['would like to share', 'be based on', 'lead us to believe'],
  },
  20: {
    id: 20,
    name: 'プロジェクトの遅延を謝罪する',
    description: '遅延の理由と今後の対策を誠実かつ具体的に説明します',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    learningGoals: [
      '遅延の事実と原因を正直に説明する',
      '謝罪の言葉と責任の所在を明確にする',
      '新しいスケジュールと再発防止策を提示する',
    ],
    sampleDialog:
      "We're really sorry for the delay. A key dependency took longer than expected, but here is our updated timeline.",
    keyPhrases: ['would like to apologize for', 'have been trying to catch up', 'plan to prevent this from happening again'],
  },
  21: {
    id: 21,
    name: '体調不良で休む',
    description: '体調不良を丁寧に伝え、業務の引き継ぎを相談する場面を想定します',
    category: 'business',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
    learningGoals: [
      '体調不良の症状（熱・頭痛など）を伝える',
      '休みたい日数と復帰予定を説明する',
      '担当業務の引き継ぎ先を相談する',
    ],
    sampleDialog:
      "I'm not feeling well today and have a fever. Would it be okay if I take the day off and hand over my tasks to a colleague?",
    keyPhrases: ['not feel well today', 'need to take the day off', 'hand over my tasks'],
  },
}

export const getScenarioDetail = (id: number): ScenarioDetail | null => {
  return SCENARIO_DETAILS[id] ?? null
}

